config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from core.dashboard.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('login/', include('core.login.urls')),
    path('pos/', include('core.pos.urls', namespace='pos')),
    path('report/', include('core.report.urls')),
    path('security/', include('core.security.urls')),
    path('user/', include('core.user.urls')),
    path('', DashboardView.as_view(), name='dashboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/pos/urls.py
from django.urls import path
from core.pos.views import POSView
from core.pos.views.account_payable.views import AccountPayableListView, AccountPayableCreateView, AccountPayableDeleteView
from core.pos.views.account_receivable.views import AccountReceivableListView, AccountReceivableCreateView, AccountReceivableDeleteView
from core.pos.views.category.views import CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView
from core.pos.views.company.views import CompanyUpdateView
from core.pos.views.credit_note.views import CreditNoteListView, CreditNoteCreateView, CreditNoteDeleteView, CreditNoteCustomerListView
from core.pos.views.customer.views import CustomerListView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView, CustomerUpdateProfileView
from core.pos.views.expense.views import ExpenseListView, ExpenseCreateView, ExpenseUpdateView, ExpenseDeleteView
from core.pos.views.expense_type.views import ExpenseTypeListView, ExpenseTypeCreateView, ExpenseTypeUpdateView, ExpenseTypeDeleteView
from core.pos.views.invoice.views import InvoiceListView, InvoiceCreateView, InvoiceUpdateView, InvoiceDeleteView, InvoicePrintView, InvoiceCustomerListView
from core.pos.views.product.views import ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, ProductStockAdjustmentView, ProductExportExcelView, ProductQrCodeView
from core.pos.views.promotion.views import PromotionListView, PromotionCreateView, PromotionUpdateView, PromotionDeleteView
from core.pos.views.provider.views import ProviderListView, ProviderCreateView, ProviderUpdateView, ProviderDeleteView
from core.pos.views.purchase.views import PurchaseListView, PurchaseCreateView, PurchaseDeleteView
from core.pos.views.quotation.views import QuotationListView, QuotationCreateView, QuotationUpdateView, QuotationDeleteView, QuotationPrintView

app_name = 'pos'

urlpatterns = [
    # tpv
    path('tpv/', POSView.as_view(), name='tpv'),
    path('tpv/search_customers/', POSView.as_view(), name='tpv_search_customers'),
    # company
    path('company/update/', CompanyUpdateView.as_view(), name='company_update'),
    # provider
    path('provider/', ProviderListView.as_view(), name='provider_list'),
    path('provider/add/', ProviderCreateView.as_view(), name='provider_create'),
    path('provider/update/<int:pk>/', ProviderUpdateView.as_view(), name='provider_update'),
    path('provider/delete/<int:pk>/', ProviderDeleteView.as_view(), name='provider_delete'),
    # category
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # product
    path('product/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/stock/adjustment/', ProductStockAdjustmentView.as_view(), name='product_stock_adjustment'),
    path('product/export/excel/', ProductExportExcelView.as_view(), name='product_export_excel'),
    path('product/qr-code/', ProductQrCodeView.as_view(), name='product_qr_code'),
    # customer
    path('customer/', CustomerListView.as_view(), name='customer_list'),
    path('customer/add/', CustomerCreateView.as_view(), name='customer_create'),
    path('customer/update/<int:pk>/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/delete/<int:pk>/', CustomerDeleteView.as_view(), name='customer_delete'),
    path('customer/update/profile/', CustomerUpdateProfileView.as_view(), name='customer_update_profile'),
    # expense_type
    path('expense/type/', ExpenseTypeListView.as_view(), name='expense_type_list'),
    path('expense/type/add/', ExpenseTypeCreateView.as_view(), name='expense_type_create'),
    path('expense/type/update/<int:pk>/', ExpenseTypeUpdateView.as_view(), name='expense_type_update'),
    path('expense/type/delete/<int:pk>/', ExpenseTypeDeleteView.as_view(), name='expense_type_delete'),
    # expense
    path('expense/', ExpenseListView.as_view(), name='expense_list'),
    path('expense/add/', ExpenseCreateView.as_view(), name='expense_create'),
    path('expense/update/<int:pk>/', ExpenseUpdateView.as_view(), name='expense_update'),
    path('expense/delete/<int:pk>/', ExpenseDeleteView.as_view(), name='expense_delete'),
    # promotion
    path('promotion/', PromotionListView.as_view(), name='promotion_list'),
    path('promotion/add/', PromotionCreateView.as_view(), name='promotion_create'),
    path('promotion/update/<int:pk>/', PromotionUpdateView.as_view(), name='promotion_update'),
    path('promotion/delete/<int:pk>/', PromotionDeleteView.as_view(), name='promotion_delete'),
    # purchase
    path('purchase/', PurchaseListView.as_view(), name='purchase_list'),
    path('purchase/add/', PurchaseCreateView.as_view(), name='purchase_create'),
    path('purchase/delete/<int:pk>/', PurchaseDeleteView.as_view(), name='purchase_delete'),
    # account_payable
    path('account/payable/', AccountPayableListView.as_view(), name='account_payable_list'),
    path('account/payable/add/', AccountPayableCreateView.as_view(), name='account_payable_create'),
    path('account/payable/delete/<int:pk>/', AccountPayableDeleteView.as_view(), name='account_payable_delete'),
    # account_receivable
    path('account/receivable/', AccountReceivableListView.as_view(), name='account_receivable_list'),
    path('account/receivable/add/', AccountReceivableCreateView.as_view(), name='account_receivable_create'),
    path('account/receivable/delete/<int:pk>/', AccountReceivableDeleteView.as_view(), name='account_receivable_delete'),
    # invoice
    path('invoice/admin/', InvoiceListView.as_view(), name='invoice_list_admin'),
    path('invoice/admin/add/', InvoiceCreateView.as_view(), name='invoice_create_admin'),
    path('invoice/admin/update/<int:pk>/', InvoiceUpdateView.as_view(), name='invoice_update_admin'),
    path('invoice/admin/delete/<int:pk>/', InvoiceDeleteView.as_view(), name='invoice_delete_admin'),
    path('invoice/admin/print/<int:pk>/', InvoicePrintView.as_view(), name='invoice_print'),
    path('invoice/customer/', InvoiceCustomerListView.as_view(), name='invoice_list_customer'),
    # quotation
    path('quotation/', QuotationListView.as_view(), name='quotation_list'),
    path('quotation/add/', QuotationCreateView.as_view(), name='quotation_create'),
    path('quotation/update/<int:pk>/', QuotationUpdateView.as_view(), name='quotation_update'),
    path('quotation/delete/<int:pk>/', QuotationDeleteView.as_view(), name='quotation_delete'),
    path('quotation/print/<int:pk>/', QuotationPrintView.as_view(), name='quotation_print'),
    # credit note
    path('credit/note/admin/', CreditNoteListView.as_view(), name='credit_note_list_admin'),
    path('credit/note/admin/add/', CreditNoteCreateView.as_view(), name='credit_note_create_admin'),
    path('credit/note/admin/delete/<int:pk>/', CreditNoteDeleteView.as_view(), name='credit_note_delete_admin'),
    path('credit/note/customer/', CreditNoteCustomerListView.as_view(), name='credit_note_list_customer'),
    # invoice print
    path('invoice/print/<int:pk>/', InvoicePrintView.as_view(), name='invoice_print'),
]

core/pos/views/account_payable/views.py
import json

from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DeleteView, CreateView, ListView

from core.pos.forms import AccountPayable, AccountPayablePaymentForm, AccountPayablePayment
from core.report.forms import ReportForm
from core.security.mixins import GroupPermissionMixin


class AccountPayableListView(GroupPermissionMixin, ListView):
    model = AccountPayable
    template_name = 'account_payable/list.html'
    permission_required = 'view_account_payable'

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST['action']
        try:
            if action == 'search':
                data = []
                start_date = request.POST['start_date']
                end_date = request.POST['end_date']
                filters = Q()
                if len(start_date) and len(end_date):
                    filters &= Q(date_joined__range=[start_date, end_date])
                for i in self.model.objects.filter(filters):
                    data.append(i.as_dict())
            elif action == 'search_payments':
                data = []
                for index, i in enumerate(AccountPayablePayment.objects.filter(account_payable_id=request.POST['id']).order_by('id'), start=1):
                    item = i.as_dict()
                    item['index'] = index
                    data.append(item)
            elif action == 'delete_payment':
                account_payable_detail = AccountPayablePayment.objects.get(pk=request.POST['id'])
                account_payable_detail.delete()
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Listado de {self.model._meta.verbose_name_plural}'
        context['create_url'] = reverse_lazy('pos:account_payable_create')
        context['form'] = ReportForm()
        return context


class AccountPayableCreateView(GroupPermissionMixin, CreateView):
    model = AccountPayablePayment
    template_name = 'account_payable/create.html'
    form_class = AccountPayablePaymentForm
    success_url = reverse_lazy('pos:account_payable_list')
    permission_required = 'add_account_payable'

    def post(self, request, *args, **kwargs):
        action = request.POST['action']
        data = {}
        try:
            if action == 'search_account_payable':
                data = []
                term = request.POST['term']
                for i in AccountPayable.objects.filter(Q(purchase__provider__name__icontains=term) | Q(purchase__number__icontains=term)).exclude(active=False)[0:10]:
                    data.append(i.as_dict())
            elif action == 'add':
                with transaction.atomic():
                    AccountPayablePayment.objects.create(
                        account_payable_id=int(request.POST['account_payable']),
                        date_joined=request.POST['date_joined'],
                        amount=float(request.POST['amount']),
                        description=request.POST['description']
                    )
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = f'Creación de un {self.model._meta.verbose_name}'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context


class AccountPayableDeleteView(GroupPermissionMixin, DeleteView):
    model = AccountPayable
    template_name = 'delete.html'
    success_url = reverse_lazy('pos:account_payable_list')
    permission_required = 'delete_account_payable'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.get_object().delete()
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Eliminación de un {self.model._meta.verbose_name}'
        context['list_url'] = self.success_url
        return context

core/pos/views/account_receivable/views.py
import json

from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DeleteView, CreateView, ListView

from core.pos.forms import AccountReceivable, AccountReceivablePaymentForm, AccountReceivablePayment
from core.report.forms import ReportForm
from core.security.mixins import GroupPermissionMixin


class AccountReceivableListView(GroupPermissionMixin, ListView):
    model = AccountReceivable
    template_name = 'account_receivable/list.html'
    permission_required = 'view_account_receivable'

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST['action']
        try:
            if action == 'search':
                data = []
                start_date = request.POST['start_date']
                end_date = request.POST['end_date']
                filters = Q()
                if len(start_date) and len(end_date):
                    filters &= Q(date_joined__range=[start_date, end_date])
                for i in self.model.objects.filter(filters):
                    data.append(i.as_dict())
            elif action == 'search_payments':
                data = []
                for index, i in enumerate(AccountReceivablePayment.objects.filter(account_receivable_id=request.POST['id']).order_by('id'), start=1):
                    item = i.as_dict()
                    item['index'] = index
                    data.append(item)
            elif action == 'delete_payment':
                account_receivable_detail = AccountReceivablePayment.objects.get(pk=request.POST['id'])
                account_receivable_detail.delete()
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Listado de {self.model._meta.verbose_name_plural}'
        context['create_url'] = reverse_lazy('pos:account_receivable_create')
        context['form'] = ReportForm()
        return context


class AccountReceivableCreateView(GroupPermissionMixin, CreateView):
    model = AccountReceivablePayment
    template_name = 'account_receivable/create.html'
    form_class = AccountReceivablePaymentForm
    success_url = reverse_lazy('pos:account_receivable_list')
    permission_required = 'add_account_receivable'

    def post(self, request, *args, **kwargs):
        action = request.POST['action']
        data = {}
        try:
            if action == 'search_account_receivable':
                data = []
                term = request.POST['term']
                for i in AccountReceivable.objects.filter(Q(invoice__customer__user__names__icontains=term) | Q(invoice__customer__dni__icontains=term) | Q(invoice__receipt_number__icontains=term)).exclude(active=False)[0:10]:
                    data.append(i.as_dict())
            elif action == 'add':
                with transaction.atomic():
                    AccountReceivablePayment.objects.create(
                        account_receivable_id=int(request.POST['account_receivable']),
                        date_joined=request.POST['date_joined'],
                        amount=float(request.POST['amount']),
                        description=request.POST['description']
                    )
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = f'Creación de un {self.model._meta.verbose_name}'
        context['list_url'] = self.success_url
        context['action'] = 'add'
        return context


class AccountReceivableDeleteView(GroupPermissionMixin, DeleteView):
    model = AccountReceivable
    template_name = 'delete.html'
    success_url = reverse_lazy('pos:account_receivable_list')
    permission_required = 'delete_account_receivable'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.get_object().delete()
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Eliminación de un {self.model._meta.verbose_name}'
        context['list_url'] = self.success_url
        return context

core/pos/templates/purchase/create.html
{% extends 'form.html' %}
{% load widget_tweaks %}
{% load static %}
{% block assets_form %}
    <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
    <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/select2-4.0.13/css/select2-bootstrap-5-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/bootstrap-touchspin-4.2.5/css/jquery.bootstrap-touchspin.css' %}"/>
    <script src="{% static 'lib/bootstrap-touchspin-4.2.5/js/jquery.bootstrap-touchspin.js' %}"></script>
    <script src="{% static 'lib/tempusdominus-bootstrap-5/js/tempusdominus-bootstrap-5.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/tempusdominus-bootstrap-5/css/tempusdominus-bootstrap-5.min.css' %}"/>
    <script src="{% static 'purchase/js/form.js' %}"></script>
{% endblock %}

{% block form_fields %}
    <div class="row">
        <div class="col-lg-2">
            <div class="form-group">
                <label>{{ form.number.label }}:</label>
                {{ form.number }}
            </div>
        </div>
        <div class="col-lg-2">
            <div class="form-group">
                <label>{{ form.date_joined.label }}:</label>
                {{ form.date_joined }}
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label>{{ form.provider.label }}:</label>
                <div class="input-group mb-3">
                    {{ form.provider }}
                    <div class="input-group-append">
                        <a class="btn btn-secondary btnAddProvider" data-url="{% url 'pos:provider_create' %}">
                            <i class="fas fa-plus"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="form-group">
                <label>{{ form.payment_type.label }}:</label>
                {{ form.payment_type }}
            </div>
        </div>
        <div class="col-lg-2">
            <div class="form-group">
                <label>{{ form.end_credit.label }}:</label>
                {{ form.end_credit }}
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <label>Búsqueda de productos:</label>
                <div class="input-group input-group-search">
                    <input type="text" class="form-control" autocomplete="off" name="search_product" placeholder="Ingrese el nombre de un producto">
                    <div class="input-group-append">
                        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-wrench"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-end" style="cursor: pointer;">
                            <a class="dropdown-item btnSearchProducts">
                                <i class="fas fa-search"></i> Buscar productos
                            </a>
                            <a class="dropdown-item btnClearProducts">
                                <i class="fas fa-times"></i> Limpiar búsqueda
                            </a>
                            <a class="dropdown-item btnRemoveAllProducts">
                                <i class="fas fa-trash-alt"></i> Borrar todo
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <table style="width:100%;" class="table table-bordered table-sm" id="tblProducts">
                <thead>
                <tr>
                    <th style="width: 5%;">Eliminar</th>
                    <th style="width: 10%;">Código</th>
                    <th style="width: 40%;">Producto</th>
                    <th style="width: 20%;">Cantidad</th>
                    <th style="width: 15%;">P./Unitario</th>
                    <th style="width: 10%;">Subtotal</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row d-flex flex-row-reverse">
        <div class="col-lg-4">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-lg-4 d-flex align-items-center">
                        <span class="fw-bold">{{ form.subtotal.label|upper }}:</span>
                    </div>
                    <div class="col-lg-8 d-flex align-items-center justify-content-start">
                        {{ form.subtotal }}
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-lg-4 d-flex align-items-center">
                        <span class="fw-bold">{{ form.tax.label|upper }}:</span>
                    </div>
                    <div class="col-lg-8 d-flex align-items-center justify-content-start">
                        {{ form.tax }}
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-lg-4 d-flex align-items-center">
                        <span class="fw-bold">{{ form.total_tax.label|upper }}:</span>
                    </div>
                    <div class="col-lg-8 d-flex align-items-center justify-content-start">
                        {{ form.total_tax }}
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="col-lg-4 d-flex align-items-center">
                        <span class="fw-bold">{{ form.total_amount.label|upper }}:</span>
                    </div>
                    <div class="col-lg-8 d-flex align-items-center justify-content-start">
                        {{ form.total_amount }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content_form_before %}
    <div id="myModalSearchProducts" class="modal fade" tabindex="-1" aria-labelledby="searchProductsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="searchProductsModalLabel">
                        <i class="fa fa-search"></i> Búsqueda de productos
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <table class="table table-bordered table-sm w-100" id="tblSearchProducts">
                            <thead>
                            <tr>
                                <th style="width: 5%;">Código</th>
                                <th style="width: 45%;">Nombre</th>
                                <th style="width: 15%;">P./Compra</th>
                                <th style="width: 15%;">P./Venta</th>
                                <th style="width: 10%;">Stock</th>
                                <th style="width: 10%;">Agregar</th>
                            </tr>
                            </thead>
                            <tbody>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="application/javascript">
        $(function () {
            purchase.detail.tax = {{ company.tax|floatformat:2 }};
            purchase.listProducts();
        });
    </script>
{% endblock %}

core/pos/templates/purchase/list.html
{% extends 'list.html' %}
{% load static %}
{% block assets_list %}
    <script src="{% static 'lib/bootstrap-daterangepicker-3.1/js/spanish.js' %}"></script>
    <script src="{% static 'lib/bootstrap-daterangepicker-3.1/js/daterangepicker.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/bootstrap-daterangepicker-3.1/css/daterangepicker.css' %}"/>
    <script src="{% static 'purchase/js/list.js' %}"></script>
{% endblock %}

{% block columns %}
    <th>Id</th>
    <th>Número de factura</th>
    <th>Proveedor</th>
    <th>Ruc</th>
    <th>Fecha de registro</th>
    <th>Tipo de pago</th>
    <th>Subtotal</th>
    <th>IVA</th>
    <th>Total</th>
    <th class="text-center">Opciones</th>
{% endblock %}

{% block javascript_list %}
    <div class="modal fade" id="myModalDetail" tabindex="-1" aria-labelledby="detailModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title fw-bold" id="detailModalLabel">
                        <i class="fa fa-search"></i> Detalle de la compra
                    </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-bordered table-sm w-100" id="tblProducts">
                                    <thead>
                                    <tr>
                                        <th style="width: 55%;">Producto</th>
                                        <th style="width: 15%;">Precio</th>
                                        <th style="width: 15%;">Cantidad</th>
                                        <th style="width: 15%;">Subtotal</th>
                                    </tr>
                                    </thead>
                                    <tbody></tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content_list_before %}
    <div class="row">
        <div class="col-lg-5 col-md-12">
            <div class="form-group">
                <label>{{ form.date_range.label }}:</label>
                <div class="input-group mb-3">
                    {{ form.date_range }}
                    <div class="input-group-append">
                        <button class="btn btn-primary btnSearchAll" type="button">
                            <i class="fas fa-calendar-check"></i> Ver todas
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <hr>
{% endblock %}